/** @type {import('tailwindcss').Config} */
export default {
	darkMode: ['selector', '[data-tw-theme="dark"]'],
	important: 'body[id][id][data-tw-theme]',
	content: ['./src/**/*.{vue,js,ts,jsx,tsx}'],
	plugins: [],
	theme: {
		extend: {
			borderRadius: {
				'nc-small': 'var(--border-radius-small)',
				'nc-element': 'var(--border-radius-element)',
				'nc-container': 'var(--border-radius-container)',
				'nc-container-large': 'var(--border-radius-container-large)',
				nc: 'var(--border-radius)',
				'nc-large': 'var(--border-radius-large)',
				'nc-rounded': 'var(--border-radius-rounded)',
				'nc-pill': 'var(--border-radius-pill)',
			},
			borderWidth: {
				'nc-input': 'var(--border-width-input)',
				'nc-input-focused': 'var(--border-width-input-focused)',
			},
			colors: {
				'nc-main-background': 'var(--color-main-background)',
				'nc-main-background-translucent': 'var(--color-main-background-translucent)',
				'nc-main-background-blur': 'var(--color-main-background-blur)',
				'nc-background-hover': 'var(--color-background-hover)',
				'nc-background-dark': 'var(--color-background-dark)',
				'nc-background-darker': 'var(--color-background-darker)',
				'nc-placeholder-light': 'var(--color-placeholder-light)',
				'nc-placeholder-dark': 'var(--color-placeholder-dark)',
				'nc-main-text': 'var(--color-main-text)',
				'nc-text-maxcontrast': 'var(--color-text-maxcontrast)',
				'nc-text-maxcontrast-default': 'var(--color-text-maxcontrast-default)',
				'nc-text-maxcontrast-background-blur': 'var(--color-text-maxcontrast-background-blur)',
				'nc-text-light': 'var(--color-text-light)',
				'nc-text-lighter': 'var(--color-text-lighter)',
				'nc-scrollbar': 'var(--color-scrollbar)',
				'nc-error': 'var(--color-error)',
				'nc-error-hover': 'var(--color-error-hover)',
				'nc-error-text': 'var(--color-error-text)',
				'nc-warning': 'var(--color-warning)',
				'nc-warning-hover': 'var(--color-warning-hover)',
				'nc-warning-text': 'var(--color-warning-text)',
				'nc-success': 'var(--color-success)',
				'nc-success-hover': 'var(--color-success-hover)',
				'nc-success-text': 'var(--color-success-text)',
				'nc-info': 'var(--color-info)',
				'nc-info-hover': 'var(--color-info-hover)',
				'nc-info-text': 'var(--color-info-text)',
				'nc-favorite': 'var(--color-favorite)',
				'nc-loading-light': 'var(--color-loading-light)',
				'nc-loading-dark': 'var(--color-loading-dark)',
				'nc-box-shadow': 'var(--color-box-shadow)',
				'nc-border': 'var(--color-border)',
				'nc-border-dark': 'var(--color-border-dark)',
				'nc-border-maxcontrast': 'var(--color-border-maxcontrast)',
				'nc-primary': 'var(--color-primary)',
				'nc-primary-text': 'var(--color-primary-text)',
				'nc-primary-hover': 'var(--color-primary-hover)',
				'nc-primary-light': 'var(--color-primary-light)',
				'nc-primary-light-text': 'var(--color-primary-light-text)',
				'nc-primary-light-hover': 'var(--color-primary-light-hover)',
				'nc-primary-element': 'var(--color-primary-element)',
				'nc-primary-element-hover': 'var(--color-primary-element-hover)',
				'nc-primary-element-text': 'var(--color-primary-element-text)',
				'nc-primary-element-text-dark': 'var(--color-primary-element-text-dark)',
				'nc-primary-element-light': 'var(--color-primary-element-light)',
				'nc-primary-element-light-hover': 'var(--color-primary-element-light-hover)',
				'nc-primary-element-light-text': 'var(--color-primary-element-light-text)',
				'nc-background-plain': 'var(--color-background-plain)',
				'nc-background-plain-text': 'var(--color-background-plain-text)',
			},
			spacing: {
				'nc-default-clickable-area-old': '44px',
				'nc-default-clickable-area': 'var(--default-clickable-area)',
				'nc-clickable-area-large': 'var(--clickable-area-large)',
				'nc-clickable-area-small': 'var(--clickable-area-small)',
				'nc-app-navigation-padding': 'var(--app-navigation-padding)',
			},
		},
	},
}
